import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { ApolloClient, InMemoryCache, gql } from '@apollo/client'

interface tProdutos {
  produtos: []
}

interface tProdutosFetch {
  name: string
  description: string
  category: string
  image_url: string

}


const Home = ({ produtos }: tProdutos) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      {produtos.map((v: tProdutosFetch, i) => (
        <ul>
          <h1>{v.name}</h1>
          <li>{v.description}</li>
          <img src={v.image_url} />
        </ul>
      ))}

    </div>
  )
}

export default Home


export async function getStaticProps() {

  //Utilizando o Apollo para consumir o GraphQL
  const client = new ApolloClient({
    uri: 'http://localhost:3333',
    cache: new InMemoryCache()
  })

  //Query GraphQL
  const { data } = await client.query({
    query: gql`
      query GetProdutos {
        allProducts {
          name
          description
          category
          image_url
        }
      }
    
    `
  })

  return {
    props: {
      produtos: data.allProducts
    }
  }
}